// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamRoleTest1.Data;

#nullable disable

namespace TeamRoleTest1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402163416_InitialiseSeededDb")]
    partial class InitialiseSeededDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamRoleTest1.Models.UserResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Analyst")
                        .HasColumnType("int");

                    b.Property<int>("Coordinator")
                        .HasColumnType("int");

                    b.Property<int>("CreativeThinker")
                        .HasColumnType("int");

                    b.Property<int>("Driver")
                        .HasColumnType("int");

                    b.Property<int>("Explorer")
                        .HasColumnType("int");

                    b.Property<int>("Finisher")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Organiser")
                        .HasColumnType("int");

                    b.Property<int>("Specialist")
                        .HasColumnType("int");

                    b.Property<int>("TeamSupporter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Analyst = 2,
                            Coordinator = 1,
                            CreativeThinker = 2,
                            Driver = 4,
                            Explorer = 0,
                            Finisher = 1,
                            FirstName = "Johhny",
                            LastName = "IronBridge",
                            Organiser = 1,
                            Specialist = 0,
                            TeamSupporter = 1
                        },
                        new
                        {
                            Id = 2,
                            Analyst = 2,
                            Coordinator = 0,
                            CreativeThinker = 2,
                            Driver = 1,
                            Explorer = 0,
                            Finisher = 2,
                            FirstName = "Janet",
                            LastName = "Springfield",
                            Organiser = 2,
                            Specialist = 0,
                            TeamSupporter = 3
                        },
                        new
                        {
                            Id = 3,
                            Analyst = 1,
                            Coordinator = 1,
                            CreativeThinker = 4,
                            Driver = 3,
                            Explorer = 0,
                            Finisher = 0,
                            FirstName = "Mark",
                            LastName = "Gravel",
                            Organiser = 2,
                            Specialist = 1,
                            TeamSupporter = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
